server:
  port: 6061
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/smart-mall?allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  #elasticsearch相关
#  elasticsearch:
#    uris: http://localhost:9200
#    #username: elastic  # 如果启用了安全认证
#    #password: your_password
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#项目目录
project:
  folder: e:/webser/web_app/smartMall/
admin:
  account: admin
  password: admin123
#日志级别
log:
  root:
    level: debug